### ISSUE TITLE
[question] Restore and email notification

### ISSUE THREAD

**Issue by PCatinean** [camptocamp/conplicity#124]
I was wondering if this solution would also include the possibility of emailing backup logs (to ensure procedures went properly) and also a way to restore the backup to the volumes in case of an accident to prevent manual restoring in the near future.

**Comment by mcanevet** [comment]
@PCatinean we think this is not the purpose of this product to manage alerting. Instead, we choose to push metrics to a Prometheus pushgateway so that you can have all kind of metrics about your backups in Prometheus. From there you can push alerts to Alertmanager which will manage the email notifications.
About a way to restore the backup, I'm not sure it's the purpose of this tool either. How would you see that?

**Comment by PCatinean** [comment]
You are right about both, as I got a bit more experience in the field I realized this is not the way to go. Thanks for the clarification!
