### ISSUE TITLE
Error: "Failed to parse Duplicity output for last full backup date of foo"

### ISSUE THREAD

**Issue by mcanevet** [camptocamp/conplicity#69]

**Comment by Pamplemousse** [comment]
It seems that this error message can be caused by several problems.

I was able to get this message for the following reasons, if this can help someone:

  * given url is not valid, or even absent
  * ssh connection failing (no compatible peer due to a restriction to algorithms not supported by paramiko)

*Use the ```-l debug``` option provide the ```stdout``` that fail to be parsed (see below).*

**Comment by Pamplemousse** [comment]
We can find the error message in the [engines/duplicity.go](https://github.com/camptocamp/conplicity/blob/master/engines/duplicity.go#L244) file. It is reached when the ```fullBackup``` is empty, and this variable contains itself the result of a regexp testing the ```stdout``` of a [```launchDuplicity```](https://github.com/camptocamp/conplicity/blob/master/engines/duplicity.go#L196-L209) call.

As it appears, this methods returns errors directly in ```stdout```, rather than populating the ```err``` variable, hence passing with no problem the errors check right after.

Reading the [LaunchDuplicity](https://github.com/camptocamp/conplicity/blob/master/engines/duplicity.go#L260-L353) implementation, it seems that all of what the container return is put into the same place ([```body```](https://github.com/camptocamp/conplicity/blob/master/engines/duplicity.go#L331-L336), then [```content```](https://github.com/camptocamp/conplicity/blob/master/engines/duplicity.go#L343)), even if it contains errors.

**Comment by mcanevet** [comment]
Maybe related to #95

**Comment by mcanevet** [comment]
Probably fixed.
